# Generated by Django 3.1.5 on 2021-01-23 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('size_m2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('min_price', models.IntegerField()),
                ('dt_created', models.DateTimeField(verbose_name='date created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlatPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_m2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('is_original_post', models.BooleanField()),
                ('is_matched', models.BooleanField(default=False)),
                ('contents_extracted', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('OTO', 'Otodom'), ('GT', 'Gumtree'), ('OLX', 'Olx'), ('DP', 'Domiporta'), ('MZN', 'Morizon'), ('WAW_N', 'Waw Nieruchomosci'), ('ADA', 'Ada'), ('GTK', 'Gratka'), ('ADS', 'Adresowo'), ('OKO', 'Okolica')], max_length=6)),
                ('url', models.URLField(max_length=300)),
                ('code', models.TextField()),
                ('heading', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('dt_posted', models.DateTimeField(verbose_name='date posted')),
                ('dt_fetched', models.DateTimeField(verbose_name='date fetched')),
                ('has_balcony', models.BooleanField(default=False)),
                ('other_info', models.TextField()),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flat_crawler.flat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
