# Generated by Django 3.1.5 on 2021-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='img_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
