# Generated by Django 3.1.5 on 2021-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0002_flatpost_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='sub_district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='is_original_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='other_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='sub_district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
