# Generated by Django 3.1.5 on 2021-01-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0003_auto_20210123_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpost',
            old_name='contents_extracted',
            new_name='failed_to_process',
        ),
        migrations.RenameField(
            model_name='flatpost',
            old_name='is_matched',
            new_name='was_matched',
        ),
    ]
