# Generated by Django 3.1.5 on 2021-01-24 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0004_auto_20210123_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpost',
            old_name='failed_to_process',
            new_name='details_added',
        ),
        migrations.RenameField(
            model_name='flatpost',
            old_name='code',
            new_name='post_soup',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='flatpost',
            name='dt_fetched',
        ),
        migrations.AddField(
            model_name='flat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='recent_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flatpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatpost',
            name='photos_signature_json',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flatpost',
            name='thumbnail',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='min_price',
            field=models.IntegerField(null=True),
        ),
    ]
