# Generated by Django 3.1.5 on 2021-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0005_auto_20210124_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='post_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
