# Generated by Django 3.1.5 on 2021-01-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0007_posthash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthash',
            name='post_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
