# Generated by Django 3.1.5 on 2021-01-24 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0009_auto_20210124_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
