# Generated by Django 3.1.5 on 2021-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0010_auto_20210124_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpost',
            name='post_soup',
            field=models.BinaryField(null=True),
        ),
    ]
