# Generated by Django 3.1.5 on 2021-01-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0011_auto_20210124_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpost',
            old_name='other_info',
            new_name='info_dict_json',
        ),
    ]
