# Generated by Django 3.1.5 on 2021-01-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0013_flat_original_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
