# Generated by Django 3.1.5 on 2021-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0014_flatpost_is_broken'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='exception_str',
            field=models.TextField(null=True),
        ),
    ]
