# Generated by Django 3.1.5 on 2021-01-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0015_flatpost_exception_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpost',
            name='was_matched',
        ),
        migrations.AddField(
            model_name='flatpost',
            name='matched_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
