# Generated by Django 3.1.5 on 2021-01-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0016_auto_20210128_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='original_post',
            new_name='recent_post',
        ),
    ]
