# Generated by Django 3.1.5 on 2021-01-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0017_auto_20210128_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='city',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='district',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='recent_price',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='size_m2',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='street',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='sub_district',
        ),
    ]
