# Generated by Django 3.1.5 on 2021-01-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0018_auto_20210128_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='recent_post',
        ),
    ]
