# Generated by Django 3.1.5 on 2021-01-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0020_flat_original_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flat_crawler.flatpost'),
        ),
    ]
