# Generated by Django 3.1.5 on 2021-01-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0021_auto_20210130_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpost',
            old_name='img_url',
            new_name='thumbnail_url',
        ),
    ]
