# Generated by Django 3.1.5 on 2021-01-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0022_auto_20210130_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='post_detailed_soup',
            field=models.BinaryField(null=True),
        ),
    ]
