# Generated by Django 3.1.5 on 2021-01-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0023_flatpost_post_detailed_soup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpost',
            name='dt_posted',
            field=models.DateTimeField(null=True, verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
