# Generated by Django 3.1.5 on 2021-01-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0024_auto_20210130_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpost',
            name='has_balcony',
            field=models.BooleanField(null=True),
        ),
    ]
