# Generated by Django 3.1.5 on 2021-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0025_auto_20210130_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='photos_bytes',
            field=models.BinaryField(null=True),
        ),
    ]
