# Generated by Django 3.1.5 on 2021-02-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0026_flatpost_photos_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id_1', models.CharField(max_length=10, null=True)),
                ('pos_id_2', models.CharField(max_length=10, null=True)),
                ('num_comparers_confirmed', models.IntegerField(null=True)),
                ('avg_score', models.FloatField(null=True)),
                ('details_json', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_match_1', to='flat_crawler.flatpost')),
                ('post_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img_match_2', to='flat_crawler.flatpost')),
            ],
        ),
    ]
