# Generated by Django 3.1.5 on 2021-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0028_auto_20210202_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagematch',
            name='num_comparers_maybe_matched',
            field=models.IntegerField(null=True),
        ),
    ]
