# Generated by Django 3.1.5 on 2021-02-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0030_auto_20210202_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpost',
            name='photos_signature_json',
        ),
    ]
