# Generated by Django 3.1.5 on 2021-02-06 15:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0033_auto_20210206_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='districts_local_names',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geolocation_json',
        ),
        migrations.AddField(
            model_name='location',
            name='districts_local_names_list',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='geolocation_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
