# Generated by Django 3.1.5 on 2021-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0034_auto_20210206_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='districts_local_names_list',
        ),
        migrations.AddField(
            model_name='location',
            name='districts_local_names',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
