# Generated by Django 3.1.5 on 2021-02-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0035_auto_20210206_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpost',
            name='street',
        ),
        migrations.RemoveField(
            model_name='flatpost',
            name='sub_district',
        ),
        migrations.AddField(
            model_name='flatpost',
            name='locations',
            field=models.ManyToManyField(null=True, to='flat_crawler.Location'),
        ),
    ]
