# Generated by Django 3.1.5 on 2021-02-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0038_auto_20210209_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='marked_as_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flatpost',
            name='locations',
            field=models.ManyToManyField(to='flat_crawler.Location'),
        ),
    ]
