# Generated by Django 3.1.5 on 2021-02-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0039_auto_20210210_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='hearted',
            field=models.BooleanField(default=False),
        ),
    ]
