# Generated by Django 3.1.5 on 2021-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0040_flat_hearted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('OTO', 'Otodom'), ('GT', 'Gumtree'), ('OLX', 'Olx'), ('DP', 'Domiporta'), ('MZN', 'Morizon'), ('WAW_N', 'Waw Nieruchomosci'), ('ADA', 'Ada'), ('GTK', 'Gratka'), ('ADS', 'Adresowo'), ('OKO', 'Okolica')], max_length=6)),
                ('triggered_dt', models.DateTimeField()),
                ('oldest_post_dt', models.DateTimeField()),
            ],
        ),
    ]
