# Generated by Django 3.1.5 on 2021-02-11 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0041_crawlinglog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlinglog',
            old_name='oldest_post_dt',
            new_name='date_fully_crawled',
        ),
        migrations.RemoveField(
            model_name='crawlinglog',
            name='triggered_dt',
        ),
        migrations.AddField(
            model_name='crawlinglog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
