# Generated by Django 3.1.5 on 2021-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0042_auto_20210211_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlinglog',
            name='date_fully_crawled',
            field=models.DateField(),
        ),
    ]
