# Generated by Django 3.1.5 on 2021-02-13 00:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0045_matchingflatpostgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('points', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
