# Generated by Django 3.1.5 on 2021-02-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0046_searcharea'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='tried_to_extract_locations',
            field=models.BooleanField(default=False),
        ),
    ]
