# Generated by Django 3.1.5 on 2021-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0047_flatpost_tried_to_extract_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='areas',
            field=models.ManyToManyField(to='flat_crawler.SearchArea'),
        ),
    ]
