# Generated by Django 3.1.5 on 2021-02-13 16:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0048_flatpost_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='area_scores',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
