# Generated by Django 3.1.5 on 2021-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0049_flatpost_area_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
