# Generated by Django 3.1.5 on 2021-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0050_flatpost_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingflatpostgroup',
            name='group_id_hash',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
