# Generated by Django 3.1.5 on 2021-03-02 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0051_matchingflatpostgroup_group_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthash',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
