# Generated by Django 3.1.5 on 2021-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_crawler', '0052_posthash_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flatpost',
            name='sub_district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
